@startuml
'https://plantuml.com/use-case-diagram

left to right direction
skinparam packageStyle rectangle
actor User
rectangle "Board" {
  User -- (Create post-it)
  (Create post-it) .> (Update board) : include
  (Update board) .> (Synchronize board) : include
  (Synchronize board) .> (Resolve conflicts) : include
  (Resolve conflicts) .> (Notify users) : include
}

@enduml