@startuml
'https://plantuml.com/class-diagram

class eCourseSystemUser <<root>> <<Entity>> {
    * FullName
    * ShortName
}
class Email <<Value object>>

class ManageMeetingInviteUI{
    + displayMeetingInvitations( List<MeetingInvite> )
    + displayMeetingInvitationsStates()
}
class ManageMeetingInviteController{
    + getAllMeetingInvitations()
    + alterMeetingInviteState( meetingInvite, inviteState )
}
class AuthorizationService{
    + session()
}

interface MeetingInviteRepository{
    + getAllMeetingInvitationsWithRecipient( email )
    + updateMeetingInviteState( meetingInvite, inviteState )
}




eCourseSystemUser - Email
eCourseSystemUser .. ManageMeetingInviteUI
ManageMeetingInviteUI .. ManageMeetingInviteController
ManageMeetingInviteController .. AuthenticationService
ManageMeetingInviteController .. MeetingInviteRepository


@enduml