@startuml
'https://plantuml.com/class-diagram

class eCourseSystemUser <<root>> <<Entity>> {
    * FullName
    * ShortName
}
class Email <<Value object>>

class ListMeetingParticipantsUI{
    + displayMeetings( List<Meeting>)
    + displayMeetingInvites( List<MeetingInvite> )
}
class ManageMeetingController{
    + getAllUserMeetings()
    + getAllParticipatingMeetings()
    + getAllMeetingIvites( meetingId )
}
class AuthenticationService{
    + session()
}
interface MeetingInviteRepository{
    + searchByMeetingID( meetingID )
}
interface MeetingRepository{
    + getAllMeetingsWithOwner( email )
    + getAllMeetingsWithParticipant( email )
}



eCourseSystemUser - Email
eCourseSystemUser .. ListMeetingParticipantsUI
ListMeetingParticipantsUI .. ManageMeetingController
ManageMeetingController .. AuthenticationService
ManageMeetingController .. MeetingInviteRepository
ManageMeetingController .. MeetingRepository

@enduml