@startuml
'https://plantuml.com/sequence-diagram
autonumber

actor Student  as Stu

activate Stu
Stu--> ":System" : asks to list future exams
activate ":System"
":System" --> Stu : shows exams
deactivate ":System"


deactivate Stu
@enduml