@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor Manager as Man

participant ":closeCourseUI" as UI
participant ":closeCourseController" as Con
participant ":Course" as Cour
database CourseRepository as Cou <<repository>>

Man -> UI : Starts asking to close a course
activate Man
activate UI

UI-> Con : getopenCourses()
activate Con


Con->Cou<<Repository>>: List<Course> Courses=getopenCourses()
activate Cou

Cou-->Con : Courses
deactivate Cou

Con-->UI: List<CourseDTO> courses
deactivate Con

UI--> Man : Shows Courses and asks to choose the courses to close
deactivate UI

Man-> UI : Selects  courses
activate UI

UI-> Con: closingCourses(List<String> courseCode)

activate Con

loop for each ID
Con->Cou<<Repository>>: findbyCode(courseCode)
activate Cou
Cou-->Con: Course
deactivate Cou
Con->Cour: closeCourse(course)

activate Cour
Cour->Cour:closeCourse
Cour->Con : status
deactivate Cour

Con->Cou<<Repository>>: add(Course)
activate Cou
Cou-> Cou: save(Course)
Cou-->Con: Status change status
end loop

deactivate Cou

Con-->UI: Status change status
deactivate Con

UI--> Man : Status change status
deactivate UI
deactivate Man
@enduml